AfricasVoices/Pipeline-Infrastructure

storage/google_drive/drive_client_wrapper.py, storage/google_drive/upload.py
I've added for now a param to update_or_create as to whether it should search in the drive root or shared folders - but I'm not 100% it's the right thing to do. Given that it's a service account, should it attempt to always find the shared folder to write in rather than default to writing in the root of My Drive?
=> Update drive client wrapper to work with service account and shared folders

storage/google_drive/drive_client_wrapper.py
(This lets me init the drive_client_wrapper.py without having to go through the hassle of writing credentials to a temporary file and then immediately reading back from that file).
=> Support initialising drive_client_wrapper from info

id_infrastructure/firestore_uuid_table.py
@marianamarasoiu PTAL - Firebase doesn't like having duplicate initialisations of a Firebase app from within the same executable
=> Constructor from an existing firebase client

id_infrastructure/firestore_uuid_table.py
@as2388 I think this is the simplest way of protecting against the partial read bug.
Testing: Introduce an import of time, and add a line at currently ln 107 with time.sleep(60) to simulate a read timeout. Without this, it will work and overwrite data, with it, it will crash on the assert
I don't think `update_data_to_uuid_mappings` is safe to use yet - but I think it is only used by the migration tool, not the pipeline?
`data_to_uuid` which is the other place that updates the mapping is already protected by an existence check
Please feel free to merge or adapt
=> Minimum fix to timeout

tools/Pipfile, tools/Pipfile.lock
0.0.4 includes the emergency prevention of the uuid recreation problem.
=> Update the version of PipelineInfrastructure used by tools to 0.0.4

storage/google_drive/drive_client_wrapper.py
500s from Drive are the most common cause of pipeline failures. This attempts to resolve by automatically retrying failed requests.
This is hard to test due to the randomness of Drive failures. If the code looks good I suggest switching a pipeline to this branch for a day or two and observing if the failure rate changes.
=> Handle HTTP 500 errors in Drive upload by retrying

storage/google_cloud/google_cloud_utils.py
408 request timeout is the most common cause of g cloud file upload failure in the pipelines. This attempts to resolve that by retrying failed requests up to 5 times and halving the chunk_size each time. If the code is okay, we will test this on a pipeline before merging.
=> handle http 408 in blob file upload by retrying in small chunk size

storage/google_drive/drive_client_wrapper.py
This adds a function for uploading a list of files to the specified folder in Drive. Using this reduces the number of Drive requests we need to make because we only need to look up the file ids in that directory once per batch, rather than for each file to upload. This should speed up analysis uploads by roughly 1.5-2x (and also leads to shorter, cleaner logging).
I refactored the error handlers into a separate _auto_retry function, which is called multiple times per update_or_create call so that partial uploads don't result in retrying all the files in the batch and so that the probability of failure doesn't increase with the number of files being uploaded.
Apologies for the poor diff, this may be easier to read raw.
=> Add drive_client_wrapper.update_or_create_batch

id_infrastructure/firestore_uuid_table.py
This speeds up repeated requests to the same uuid table instance and, more importantly, drastically reduces the number of Firestore reads needed. Testing on JPLG-2020, this reduces the number of documents read from Firestore from 347220 per run of fetch raw data to 23148, with the only change needed in the pipeline being a version number bump in the Pipfile.
=> Add caching to FirestoreUuidTable

storage/google_drive/drive_client_wrapper.py
This should make it easier to diagnose problems. At the moment if a file in a batch upload fails we don't know which particular file actually failed.
=> Include file names in more logs in Google Drive upload

storage/google_drive/drive_client_wrapper.py
Adds a flag 'fix_duplicates' to the upload functions which, if set, automatically handles duplicated files on Drive by removing the duplicates, then uploading again. This will allow us to handle Drive consistency problems automatically rather than needing to manually intervene to delete problematic files, and therefore solves one of the biggest causes of pipeline failures in G&A. 
It's added as a flag which defaults to False because automatically deleting files just because they have the same name is a bit of a scary thing to do in general, but should be fine for pipeline uploads. As an added safety, if the service account attempts to delete files it doesn't own, the delete operation will fail.
=> Automatically fix duplicates on Drive

setup.py
This is needed because dependency_links has been removed from pip
=> Fix dependency links

id_infrastructure/firestore_uuid_table.py
This PR includes the API updates we need to export uuid tables (for the purposes of back-ups and archiving).
These are:
- The addition of a new FirestoreUuidInfrastructure class for getting and listing the available tables
- Writes to the table parent doc when data is added, to ensure that the table is visible in collection queries
- A new get_all_mappings function on uuid tables.
- Reworked constructors to support multiple table instances being created, and to allow tables to co-exist with other Firestore clients in future. Unfortunately this is a breaking change, as python doesn't support multiple constructors.
=> Update firestore_uuid_table.py to support exporting mapping tables

engagement_database/data_models.py
Expected use is that you provide a new doc and a HistoryEventOrigin to every set api for the database, then the set methods take care of constructing the HistoryEvent correctly and making sure that all the updates commit in the same batch e.g. `Database.set_message(message: Message, origin: HistoryEventOrigin): void` would update the messages and history sub-collections appropriately.
I think these objects contain enough detail to localise every update to the line of code that created it (across projects and versions), as well as providing the flexibility to accept any kind of source data/descriptions in `details`, but do suggest anything else that would be useful. We'll still need to test that we can do rollbacks before any engagement db project can enter production.
=> Add data models needed to support history

engagement_database/data_models.py
This brings history entries in line with the same approach we used for Messages.
=> Include history entry id in the history entry objects

engagement_database/__init__.py, engagement_database/engagement_database.py
Review #46 first.
Notes:
- get_messages exposes the underlying Firestore query for filtering for now, because I'm not sure if it makes to provide a python wrapper yet, or exactly what that wrapper's going to need to constrain the possible queries to.
- This supports multiple databases in the same firestore, for flexibility if we need it.
- This puts messages and history in top-level collections relative to the database, rather than under contacts as we had previously discussed. This is because from experimentation I needed collection group queries with special indexes to make that design work - it's much easier to change to a flat collection and query messages where participant_uuid == target_id to get the messages from the same participant.
=> Support getting and setting messages from the engagement database

id_infrastructure/firestore_uuid_table.py
- Reduces logging noise from uuids that already exist.
- Prints the new uuid only, so phone numbers don't show up in logs.
=> Tidy up logs in data_to_uuid

engagement_database/data_models.py
This lets us set and query by a message's id in its origin dataset e.g. for rapid pro this id would be generated from the workspace/flow/run/result ids. This gives us an alternative means of checking if we've already added a message (which gives us protection against rapid pro's timestamps changing on archiving), and could be extended in future to include super easy access to other origin details, which greatly speeds up debugging.
=> Add origins to each Message object

engagement_database/engagement_database.py
This brings the created object in line with the docstring in the data model itself.
=> Write path as str rather than as DocumentReference

engagement_database/engagement_database.py
This is needed to support db rollbacks. Under normal use we'd prefer to use the archived/anonymised flags.
=> Add delete_doc

engagement_database/data_models.py
I think we should add this so we can easily filter by or check where messages came from in future if we need to
=> Add origin_type to MessageOrigin

engagement_database/data_models.py
This will help prevent https://github.com/AfricasVoices/Test-Pipeline-Engagement-DB/pull/180 from reoccurring.
=> Validate origin details, so we don't accidentally write something that isn't serializable

engagement_database/engagement_database.py
We have a couple of places where we need to do large database reads, which requires special batching code to avoid the Firestore connection timing out. This puts that batching into the get_messages function itself, so it will be easy to opt in to it in all the places we need it.
=> Support optional batch fetching in EngagementDatabase.get_messages

engagement_database/engagement_database.py
This will be useful anywhere we need to retrieve a large history, but the main motivator right now is rolling-back more than a few days.
=> Add optional batch_fetch mode to get_history
